---
title: "2019-04-24-Jeffery"
author: "Jeffery"
date: "2019年4月24日"
output: html_document
---

```{r}
m2<-matrix(c("a","b","c","d"),2,2)
class(m2)
typeof(m2)
a<-m2[[1]]
c<-m2[[3]]
bd<-m2[2,]
a
c
bd
```

```{r}
StuList <- list(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuList 
```

```{r}
StuList <- list(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuList 
StuList[[2]][3]
```

```{r}
StuDF <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuDF 



StuDF
StuDF[[2]][[3]]
```

```{r}
as.data.frame(StuList) -> StuDF3

class(StuDF3)
```

```{r}
StuDF3
```

```{r}
as.data.frame(StuList,stringsAsFactors = F) -> StuDF4
class(StuDF4)
```

```{r}
StuDF4
```

```{r}
chosenletter <- LETTERS[1:15]
lettermatrix <- matrix(chosenletter,3)
lettermatrix
```

```{r}
chosenLETTERS <- LETTERS[1:15]
matObj1 <- matrix(chosenLETTERS,5,3)
matObj1
matObj1[c(T,F,F,T,F),c(F,T,T)]
```

```{r}
dim(classSurvey)
classSurvey[c(1:60),c(4,5)]
classSurvey[,c(4,5)]

```